linux/debian/daily/kivy-tools.install
Fixes problems because of removed files at kivy/kivy@master
=> Files at packaging/win/* and packaging/osx/* have been moved to kivy/kivy-sdk-packager

linux/debian/daily/python-kivy.install, linux/debian/daily/python3-kivy.install
since they got removed along listview in commit
d78d435a383dfd37ce3f1b047c344b2f86ded809 of kivy.
=> remove references to adapters in daily ppa

osx/data/script
Running  `exec "${SCRIPT_PATH}/python"` breaks our virtualenv.
Output of `import sys; print(sys.path)` when using `exec ${SCRIPT_PATH}/python`:
```
['', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
```
Output of `import sys; print(sys.path)` when using `exec python`:
```
['', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Applications/Kivy.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3. …
```
=> Fixes "kivy" not found on macOS

ci/osx_ci.sh, osx/create-osx-bundle.sh
During #67 `data/kivy_activate` was mistakenly not copied into bundle.
=> Add missing kivy_activate

linux/debian/daily/rules, linux/debian/stable/rules
The following dependencies,  are not needed anymore (and are failing to build):
- setuptools
- pip
- wheel
- packaging
=> Removes linux/debian dependencies in build script

linux/debian/daily/python3-kivy.install, linux/debian/stable/python3-kivy.install
This PR adds `kivy/eventmanager` that have been introduced in  https://github.com/kivy/kivy/pull/7658
=> Add kivy/eventmanager

osx/create-osx-bundle.sh
Getting the error: 
```
bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/runner/work/glitter2/kivy-sdk-packager/osx/Glitter2.app/Contents/Frameworks/SDL2_ttf.framework
```
when code signing as described here: https://blog.inventic.eu/2015/03/os-x-codesign-failed-bundle-format-is-ambiguous-could-be-app-or-framework/.
=> Have to use capital R for cp, otherwise codesign may fail

.github/workflows/test_macos.yaml
- Same of https://github.com/kivy/kivy/pull/7885
- https://github.com/actions/runner/releases/tag/v2.292.0 now supports Apple Silicon natively. 🥳
- The run_wrapper that was enforcing arm64 on top of a x86_64 process is now un-needed.
- There's a pending PR in actions/python-versions which is expected to introduce support for universal2 versions of Python, so hopefully, we will be able to rely on actions/setup-python also for our self hosted runner in a while..
=> Our self-hosted Apple Silicon runner now has been migrated to actions/runner v2.292.0 which now supports arm64 natively

osx/data/script
We are not allowed to edit the .app for security reasons. This fix only fixes KIVY_HOME. There would be other fixes needed to enforce the .app to be static and not have any __pycache__ or another intermediary files that changes the .app
=> Use ~/Library/Application Support/$BUNDLE_ID for KIVY_HOME

ci/windows_ci.ps1, win/sdl2.py
**Windows:**
- Bumps SDL2 to `2.24.0` (the same pinned in `kivy/kivy` for macOS and Linux wheels)
- Bumps  SDL2_mixer to `2.6.2`  (the same pinned in `kivy/kivy` for macOS and Linux wheels)
- Bumps  SDL2_ttf to `2.20.1`  (the same pinned in `kivy/kivy` for macOS and Linux wheels)
- Bumps  SDL_image to `2.6.2`  (the same pinned in `kivy/kivy` for macOS and Linux wheels)
- Bumps `kivy_deps.sdl2_dev` and `kivy_deps.sdl2` to `0.4.6`
PS: `git://github.com/kivy/kivy.git` was failing.
⚠️ When merging into `master`, we should add `[publish sdl2 win]` into the commit message.
=> Windows: SDL2 to 2.24.0, SDL2_mixer to 2.6.2, SDL2_ttf to 2.20.1, SDL_image to 2.6.2

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml, win/angle.py, win/gstreamer.py, win/sdl2.py
- `angle`: There's at least a new commit since our last release, so the new artifact will be different. That means we need to also bump the version (from `0.3.2` to `0.3.3`)
- `glew`: No new releases here. Kept the version to `0.3.1` (Upload to pypi will fail for `3.7`,`3.8`,`3.9`,`3.10`)
- `sdl2`: SDL2 `2.24.1` has been released, so there's a chance to upgrade here. Bumped version from `0..5.0` to `0.5.1`
- `gstreamer`: There's a (non-bugfix) release for that package. Bumped version from `0.3.4` to `0.4.0`
Check if builds:
All the dependencies will fail the latest test step on `3.11`. This is expected.
**Reminder**: Add `[publish sdl2 win] [publish gstreamer win] [publish glew win] [publish angle win]` on commit message.
=> Add support for Python 3.11 and bump dependencies to latest versions

ci/windows_ci.ps1, win/gstreamer.py
From @matham on https://github.com/kivy/kivy-sdk-packager/pull/82 :
> I'm think with gstreamer we probably don't need to release updates more than once or twice a year, because the files are quite large and the fixes are not really urgent. Last time I asked about this on pypi-support nothing happened.
I'd suggest to remove the 0.4.0 release from pypi and instead only release the 3.11 wheels for 0.3.3. No one should have used 0.4.0 yet, because kivy is locked to 0.3.x so removing it should be fine.
I've been away from my laptop for more than a week and even delivered some Kivy t-shirts to our fellow in Amsterdam, but unfortunately still no reply from `pypi-support` 😂
Considering that there's an urge to test everything on `3.11` and schedule a new Kivy release:
- Reverted our gstreamer …
=> Revert to a previous gstreamer version - we can't publish wheels > 150M on PyPi

win/sdl2.py
- SDL2 dependencies internal version has been bumped to `0.6.0` (SDL2 changed from `2.24.1` to `2.26.4`)
- Bumped `SDL_image`, `SDL_ttf` and `SDL_mixer` bugfix versions.
- `angle` and `glew` have not been updated, so a new release is not needed.
- `gstreamer` has been updated, but we decided to not update it to avoid polluting PyPI: https://github.com/kivy/kivy-sdk-packager/pull/84
⚠️ When merging into master, we should add `[publish sdl2 win]` into the commit message.
Ref: https://github.com/kivy/kivy/issues/8167
=> Bump dependencies versions before Kivy 2.2.0

linux/debian/daily/rules, linux/debian/stable/rules
Installing Python packages during PPA builds is a headache, since `pip install this-package` just does not work. (build machines does not have access to public internet).
The only way is to manually build and install packages from sources, which is a pain if the packages have multiple sub-dependencies, since sources need to be made available via a synced repo in launchpad. (again, can't use the public internet).
Since `sphinxcontrib.jquery` is not needed here, instead of getting mad, we just avoid to use the dependency by patching the needed files. (patches are hosted at https://code.launchpad.net/~misl6/kivy/+git/kivy-ppa-patches in `main` and `stable` branches). The patches repo is added via the recipe on Launchpad UI.
=> Apply patches to avoid usage of `sphinxcontrib.jquery` module.

linux/debian/stable/changelog
- Updates changelog for `stable`, which is now at release 2.2.1
=> Update Ubuntu PPA stable to 2.2.1

.github/workflows/windows_sdl2_wheels.yml, win/sdl2.py
- ~~We were waiting for an update on `SDL_image`, in order to avoid multiple releases in a short time, but since there's no update, better to move ahead.~~
- Bump `sdl2` from `2.26.4` to `2.28.5`, bump `sdl_image` from `2.6.3` to `2.8.0` (and therefore our internal version moved from `0.6.0` to `0.7.0`
- Added Python `3.12` to supported matrix for `sdl2` deps.
- Updated Github Actions
- Fixes https://github.com/kivy/kivy/issues/8200
=> [publish sdl2 win] Update `sdl2` and `sdl_image` versions and add Python `3.12` to supported matrix

.github/workflows/windows_angle_wheels.yml, ci/windows_ci.ps1, win/angle.py
Adds Python `3.12` to matrix for `angle` and updates Github Actions for related jobs.
- Bump `angle` from `chromium/4758` to `chromium/6045` (See https://chromiumdash.appspot.com/branches and https://github.com/google/angle/blob/main/doc/ChoosingANGLEBranch.md for how to choosing an ANGLE branch to track)
- Change the version for `kivy_deps.angle` from `0.3.3` to `0.4.0`
Keeping the previous version was not possible as:
- `windows-latest` can't build `chromium/4758`, does not provide the proper Visual Studio setup.
- [A change in depot_tools](https://groups.google.com/a/chromium.org/g/chromium-dev/c/xFYvFYGQUGI) broke the build of `chromium/4758` even on `windows-2019`
✅ Tested locally on Windows 11 x86_64
⚠️ Add `[publish angle win]` before merge.
=> [publish angle win] Update `angle` version and add Python `3.12` to matrix for `angle` and update Github Actions for related jobs

CODE_OF_CONDUCT.md, CONTACT.md, CONTRIBUTING.md, LICENSE, README.md, osx/README.md, win/common.py
This is part of an effort to make the Kivy sibling projects' documentation structure consistent and up-to-date.
Unrelated items:
* Readme was vestigial. Wrote description from scratch.
CHECKLIST
* CONTRIBUTING.md
[x] If repo takes user contributions, is present
[x] In root dir (not .github dir)
[x] Explains relationship to Kivy, if unclear.
[x] Refers to kivy/kivy Contribution Guidelines.
* LICENSE
[x] If repo takes user contributions, is present.
[x] Acknowledges the range of years to 2023.
[x] Acknowledges Kivy Team and other contributors
[x] Mentions it is an MIT License.
* CODE_OF_CONDUCT.md
[x] If repo takes user contributions or hosts discussions, is present.
[x] Refers to kivy/kivy CODE_OF_CONDUCT.md
* CONTACT.md
[x] Refers to kivy/kivy CONTACT.md
* FAQ.md
[NA] If repo is big …
=> Make doc structure consistent and up-to-date

.github/workflows/test_macos.yaml, ci/osx_ci.sh, osx/README.md, osx/create-osx-bundle.sh, osx/prepare-wheels.py, osx/requirements.txt
- Introduces `prepare-wheels.py` to download `universal2` wheels when available, or to merge non-universal2 ones to avoid at all costs building from source, as it adds complexity (for us, and for users).
- Improve docs
- Update `create-osx-bundle.sh` to use `prepare-wheels.py`
- Removes the now un-needed complexity to handle `apple-silicon-m1` builds (As now `actions/setup-python` supports Apple Silicon runners)
- Updates Github Actions versions
`prepare-wheels.py` is just the first step to making macOS packaging more reliable. The whole macOS packaging toolset needs a refresh, but ATM that's enough to handle the next Kivy release.
=> Update `create-osx-bundle.sh`, introduce `prepare-wheels.py` to merge non-universal2 wheels.

osx/prepare-wheels.py
`parse_requirement` raises a `SyntaxError` when dependencies refer to a local path (E.g. `kivy[base] @ file:///Users/mirko/Documents/projects/kivy`).
This PR allows local paths in the requirements file.
=> Handle `SyntaxError` on `parse_requirement` to allow `file://` paths in requirements file

.github/workflows/windows_sdl3_wheels.yml, win/build_sdl3.ps1, win/sdl3.py
This PR introduces the new `sdl3` and `sdl3_dev` packages for Kivy 3.0.0.
ATM build is performed on `sdl`, `sdl_mixer`, `sdl_image`, `sdl_ttf` main branches, as SDL3 (and sub libs) is still under development.
For this reason, similarly to `angle`,  we will be required to bump the version if something changed on the main branch.
However, I expect SDL3 to be released before Kivy 3.0.0, so things will be more stable in future.
Differently from`kivy_deps.sdl2`, the `kivy_deps.sdl3` packages are built from source, so we can customize our builds, and apply patches faster.
Additionally, it will be quite straightforward to support more architectures in the future.
=> Add SDL3 wheels for `kivy_deps.sdl3` and `kivy_deps.sdl3_dev` [publish sdl3 win]

win/sdl3.py
Builds SDL3 on top of the latest `main` branch commits.
A lot of things changed from the first release (`0.0.1`) which is now incompatible with https://github.com/kivy/kivy/pull/8666
=> Bump SDL3 recipe version to produce new release (`0.0.2`)

.github/workflows/windows_glew_wheels.yml
As said [here](https://github.com/kivy/kivy-sdk-packager/pull/108#issuecomment-2380578998), `v4` artifacts are not mutable and our pipeline takes advantage of mutable artifacts.
A migration to support `v4` version (as `v3` will be deprecated, soon or later) will be applied in future.
For now, better sticking with `v3` version.
=> Use `actions/upload-artifact@v3` instead of `actions/upload-artifact@master`

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml
To reflect changes made in both `master` and `devel-2.3.x` `kivy/kivy` branches, removes Windows 32-bit support for `kivy.deps` artifacts.
The `arch` logic is not been removed yet as could be used in future to support `arm64` artifacts.
=> Remove Windows 32-bit support for `kivy.deps` artifacts

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml
Python 3.7 version reached its EOL a long time ago, and support has been removed from both `master` and `devel-2.3.x` `kivy/kivy` branches.
=> Remove Python 3.7 support for Windows `kivy.deps` artifacts

win/gstreamer.py
Gstreamer `1.18.5` has been removed from gstreamer releases mirror, and therefore we're unable to process new builds.
This PR bumps `gstreamer` to bugfix release `1.18.6`
=> Bump gstreamer to `1.18.6`, as `1.18.5` is not downloadable anymore

.github/workflows/windows_angle_wheels.yml, ci/windows_ci.ps1
Fixes build not completing due to Python unavailability.
Uses `actions/setup-python` and removes hacky fix that prevents Python to be available in PATH.
=> Setup Python before processing ANGLE build

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml, .github/workflows/windows_sdl3_wheels.yml
Failures for `3.13-dev` tests are expected as other deps are not yet available.
Will release `gstreamer` now (as version has already been bumped in #120) and other dependencies during the day.
=> Add Python `3.13-dev` to build matrix for Windows deps

win/sdl2.py
Bump SDL2 deps versions for Windows `kivy.deps` artifacts to reflect https://github.com/kivy/kivy/pull/8836
✅ Tested on Windows 11
=> Bump SDL2 deps versions for Windows `kivy.deps` artifacts

linux/debian/daily/changelog
Set `daily` changelog to version `2.3.1`, so it reflects the version built on launchpad
=> Set linux/debian `daily` to version `2.3.1-dev` to reflect recipe in launchpad

linux/debian/daily/rules
PPA builds are performed in a isolated machine with no access to pypi servers, and should use `python3-*` deb packages as a replacement for pip-installable packages.
The required versions for build-time requirements cannot be used in this case. This should not be an issue ATM.
This PR applies a patch to `kivy/kivy` code, so a relaxed version of `setuptools` and other build-time-only tools can be used.
=> Apply `use-relaxed-build-time-reqs-versions.patch` while building daily ppa

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml, .github/workflows/windows_sdl3_wheels.yml
- Python `3.8` has been removed as reached EOL on 2024-10-07
- Minimum supported version in Kivy is now Python `3.9` (https://github.com/kivy/kivy/pull/8935)
=> Remove support for Python 3.8 on Windows wheels as it reached EOL

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml, .github/workflows/windows_sdl3_wheels.yml
🧹 Python 3.13 has now been released, move Windows wheels build matrix from 3.13-dev to 3.13
=> Python 3.13 has now been released, move Windows wheels build matrix from 3.13-dev to 3.13

win/build_sdl3.ps1, win/sdl3.py
This pull request updates the SDL3 dependencies and their associated build scripts to use the latest versions. It also increments the version of the `sdl3.py` script to reflect these changes.
* Updated `SDL3` version from `3.2.4` to `3.2.10`
* Updated `SDL3_image` version from `3.2.0` to `3.2.4`
* Introduced a versioned release for `SDL3_ttf` (version `3.2.2`), replacing the previous unversioned main branch reference, and updated the download URL and folder name in `win/build_sdl3.ps1`.
* Rebuild `SDL3_mixer` from `main`
* Incremented the `__version__` in `win/sdl3.py` from `0.0.5` to `0.0.6` to reflect the changes.
=> Bump `SDL3` to `3.2.10`, `SDL3_image` to `3.2.4`, set `SDL3_ttf` to use release `3.2.2` and rebuild `SDL3_mixer` from `main` [publish sdl3 win]

.github/workflows/windows_angle_wheels.yml, .github/workflows/windows_glew_wheels.yml, .github/workflows/windows_gstreamer_wheels.yml, .github/workflows/windows_sdl2_wheels.yml, .github/workflows/windows_sdl3_wheels.yml, ci/windows_ci.ps1
As now kivy moved to `sdl3`, we must ensure the proper `KIVY_GL_BACKEND` is used while testing the artifacts.
`angle_sdl2` has been removed, but has been kept as a reference in `windows_sdl2_wheels` in case we need to produce new `sdl2` wheels for maintenance  versions of Kivy. In that case we will need to perform some changes to the test script to ensure the proper version of Kivy is used.
=> Ensure the proper `KIVY_GL_BACKEND` is used while testing the artifacts

win/build_sdl3.ps1, win/sdl3.py
[windows_ci run](https://github.com/DexerBR/kivy-sdk-packager/actions/runs/16663894393)
=> Bump SDL3 version to the latest stable release (`3.2.22`) [publish sdl3 win]
